branch-defaults:
  default:
    environment: bio-env
    group_suffix: null
  master:
    environment: bio-env
environment-defaults:
  bio-env:
    branch: null
    repository: aws
global:
  application_name: lbd-explorer
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python2.7
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
